### ISSUE TITLE
ESM imports/exports are not used in compiled library

### ISSUE THREAD

**Issue by rupansh** [algorand-devrel/beaker-ts#18]
Hey

ESM requires that all exports/imports must include the file extension.
However the compiled library on npm doesn't use proper esm imports and dont have an extension.
This in-turn causes the following errors when importing beaker-ts in a frontend app using CRA:

```
ERROR in ./node_modules/beaker-ts/lib/index.js 7:0-38
Module not found: Error: Can't resolve './sandbox' in '<censored>/node_modules/beaker-ts/lib'
Did you mean 'index.js'?
BREAKING CHANGE: The request './sandbox' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

**Comment by barnjamin** [comment]
Hey @rupansh, thanks for pointing this out.  

Do you happen to know the "right" fix for this? 

Seems like there are a lot of options including just adding something to a project local webpack file. If there is a tweak I can make to make it easier for lib users tho I'm game

**Comment by rupansh** [comment]
> Hey @rupansh, thanks for pointing this out.
> 
> Do you happen to know the "right" fix for this?
> 
> Seems like there are a lot of options including just adding something to a project local webpack file. If there is a tweak I can make to make it easier for lib users tho I'm game

Hey
as a workaround I just changed beaker-ts to compile to cjs
npm libs ship both a cjs and an esm build in their package for cross compatibility.
It would require a packer to be added to your build pipeline of course

**Comment by barnjamin** [comment]
I removed the `module` directive and set tscofnig to module: commonjs and was able to import it into a CRA app.

If someone else comes across this please re-open
