### ISSUE TITLE
Is beaker-ts intended to use in browser?

### ISSUE THREAD

**Issue by jeron-diovis** [algorand-devrel/beaker-ts#20]
I have an application client generated by `beaker-ts` (version `0.0.61`, if it matters).
I want to use it in my frontend application (based on `create-react-app@5`).

```sh
yarn add create-react-app 
yarn create react-app beaker
```

```tsx
// beaker/src/App.tsx
import { MainContract } from './maincontract_client'
const app = new MainContract({ ...whatever... })
```

With that, on running `yarn start` to build my project I get this:
<img width="833" alt="Screenshot 2022-12-15 at 11 01 04" src="https://user-images.githubusercontent.com/2756868/207839613-d9dcde5b-52f5-494a-8ee0-4c47899e53d7.png">

Given recommendation of adding explicit fallback can be done using `react-app-rewired`:
```
yarn add react-app-rewired customize-cra
yarn add crypto-browserify
```
```js
// beaker/config-overrides.js
const { override } = require('customize-cra')

module.exports = override(
  cfg => {
    Object.assign(cfg.resolve, {
      fallback: {
        "crypto": require.resolve("crypto-browserify")
      }
    })
    return cfg
  }
)
```
```
npx react-app-rewired start
```

But with that, I just get same issue with another package:
<img width="807" alt="Screenshot 2022-12-15 at 12 02 16" src="https://user-images.githubusercontent.com/2756868/207842275-5ff7d1fb-497d-4b19-8739-d643b0ee6bf0.png">

I didn't try to mock it up too.

---

Instead I tried to downgrade my app to webpack@4, in hope that it will cover all these issues with built-in polyfills. 
```
yarn add react-scripts@^4 # this will update installed webpack version too
```
But with that it got even worse:
<img width="1192" alt="Screenshot 2022-12-14 at 17 09 54" src="https://user-images.githubusercontent.com/2756868/207802018-fc30e83c-7f92-4db0-b6c5-e3f31e1fe731.png">

This is something really really weird. Like beaker source code can't be handled by `babel-loader` at all.

---

And besides of all that, it also gives a whole bunch of warnings, because `typescript` package is also included in bundle somewhere:
<img width="853" alt="Screenshot 2022-12-15 at 13 01 09" src="https://user-images.githubusercontent.com/2756868/207843021-5b78f690-67db-4d78-9f6a-686e7a5da9f7.png">

---

So, maybe I got smth wrong and generated beaker client is NOT intended to use on frontend? It is a something for Node applications only?
Or if it is – then how do I properly solve all those issues above?

**Comment by barnjamin** [comment]
it _is_ meant to be useful for the browser environment but it turns out I'm bad at knowing how to properly package it.

I've got a couple examples here: 
https://github.com/algorand-devrel/hello-beaker 
https://github.com/algorand-devrel/coin-flipper/

But both use React but vite for packaging.



I set up a CRA app to try it but had to eject CRA and modify the `config/webpack.config.js` to add a fallback for crypto:
```js
    resolve: {
     // ...
      fallback: {
        crypto: false
      },
      // ...
      ```
 and my tsconfig looks like:
 ```
 ben@Algo-Guidarelli:~/my-app$ cat tsconfig.json
{
  "compilerOptions": {
    "target": "ES6",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "CommonJS",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": [
    "src"
  ]
}
```

This pr is meant to improve the situation a bit for the algosdk requirement but hasnt been released yet:
https://github.com/algorand/js-algorand-sdk/pull/707
 
I'll have to dig in again with another CRA example to see if I can replicate the above.  If you dig in to the package I'm more than happy to take any prs or observations you might have about the packaging

**Comment by jeron-diovis** [comment]
Ok, I can't address packaging issue directly for now, but at least I managed to patch it around im my project.

For those who are using react-app version 5: with `react-app-rewired`, I had to add following in my `config-overrides.js`:
```js
const { override } = require('customize-cra')
const { ProvidePlugin } = require('webpack')

module.exports = override(
  function resolveAlgoIssues(config) {
    config.resolve.fallback = {
      crypto: false, // or use `require.resolve('crypto-browserify')`
    }
    
    // exclude code-generation stuff which definitely isn't need in browser
    config.module.rules.push({
      test: require.resolve('beaker-ts/lib/generate/generate'),
      use: 'null-loader',
    })

    // Node's `Buffer` is used directly somewhere in algosdk code
    config.plugins.push(
      new ProvidePlugin({
        Buffer: ['buffer', 'Buffer'],
      })
    )

    return config
  }
)
```
Or eject your app and do the same directly in webpack config.
With that, it compiles and runs fine for me.

---

As for react-app version 4, I didn't manage to make it work. Tried to manually override many babel-related dependencies here and there, to make it match ones from react-app@5, but nothing helped so far. It still crashes as shown on screenshot above.
