### ISSUE TITLE
Generated application client incorrectly extends basic `ApplicationClient` class

### ISSUE THREAD

**Issue by jeron-diovis** [algorand-devrel/beaker-ts#21]
If contract has methods with same names as ones in `ApplicationClient` ts class, then generated app client will be considered invalid by typescript.

```py
from pyteal import *
from beaker.decorators import external
from beaker.application import Application

class GenApp(Application):
    @external
    def resolve(self, decision: abi.String, output: abi.String):
        return Seq(
            Log(Bytes("Decision is made")),
            output.set(decision)
        )
```

<img width="990" alt="Screenshot 2022-12-23 at 16 28 29" src="https://user-images.githubusercontent.com/2756868/210356747-e49ac68f-ebc1-49e7-a764-eed710820a10.png">

---

Since contract developer obviously doesn't have to be aware of ts class structure, the only more or less reasonable way for FE dev to bypass this for now is to manually add `// @ts-nocheck` directive in such problematic clients (or `// @ts-ignore` for each of such methods).

And since generated file isn't assumed to be manually edited anyway – maybe it's worth to inject these directives automatically?

**Comment by barnjamin** [comment]
makes sense to fix, wdym inject directives automatically?

I'd probably just end up renaming the app client specific methods like `resolve` to `_resolve` so they'd be less likely to clash but your thing sounds like maybe you've got a better idea?

**Comment by jeron-diovis** [comment]
Some methods of base contract are meant to be used directly – `create` / `optIn` / `execute` etc. Renaming them all as `_name` will look like developer should not call them manually. Not sure it'd be a good design. Although technically it'll work, of course.

Maybe `resolve` specifically can be renamed like that – it looks like some internal logic. But in actual app we're currently developing one contract has external methods `create` and `delete` – unlikely these methods in base `ApplicationClient` should be named like they are 'protected'.

How about slightly renaming generated methods instead? Smth like `abi_create`, `abi_resolve`. 
It looks quite logically (I guess) and it guarantees an absence of any clashes ever.

**Comment by barnjamin** [comment]
I've tweaked the `resolve` method to `_resolve` for now and pushed some changes to bump sdk version to 2.0
