### ISSUE TITLE
example without a client

### ISSUE THREAD

**Issue by xpanvictor** [algorand-devrel/beaker-ts#26]
usage by creating transactions and signing with user's wallet should be provided

**Comment by barnjamin** [comment]
Can you say more about what you're looking for?

Have you seen https://github.com/algorand-devrel/hello-beaker for example?

**Comment by xpanvictor** [comment]
oh, that's what I need. Needed help using getting a signer. I basically prepare the transaction from one end and send it to another to sign it. But that example is good
