### ISSUE TITLE
[ Question ] Decoding Address values from state

### ISSUE THREAD

**Issue by MrJackdaw** [algorand-devrel/beaker-ts#27]
Greetings! I come bearing one more (probably small and silly) question. 

I created a contract with a few state values, two of which are `Addresses` (using `Tealtype.bytes` as shown in the examples). 

But when I read the state (using `client.getApplicationState()`), those two addresses are not encoded in UTF-8 -- presumably because beaker doesn't know about [and therefore, what to do with] them. 

So I get these values instead: how do I decode them?

<img width="408" alt="Screenshot 2023-02-08 at 7 18 53 AM" src="https://user-images.githubusercontent.com/6107109/217571861-f388a48a-8793-4d0f-8d1a-2482313728f8.png">

### Additional note
The _contract_ is aware of them and can use them just fine. I created a transaction that returns them as an `abi.NamedTuple`, and they come through as expected that way -- but it is a slower call than `getApplicationState`.

**Comment by barnjamin** [comment]
https://github.com/algorand-devrel/beaker-ts/blob/master/src/application_client/application_client.ts#L480 you can pass `raw=true` to the method and then use `algosdk.encodeAddress` to get the address as the 58 byte address

**Comment by MrJackdaw** [comment]
> https://github.com/algorand-devrel/beaker-ts/blob/master/src/application_client/application_client.ts#L480 you can pass `raw=true` to the method and then use `algosdk.encodeAddress` to get the address as the 58 byte address

Thanks as always for a speedy response!
