### ISSUE TITLE
Typescript deprecation warning v4.8.0

### ISSUE THREAD

**Issue by aorumbayev** [algorand-devrel/beaker-ts#30]
## Description

Started receiving a deprecation warning during invocation on beaker-ts:

```
DeprecationWarning: 'createImportDeclaration' has been deprecated since v4.8.0. Decorators are no longer supported for this function. Callers should switch to an overload that does not accept a 'decorators' parameter.
```

## Steps to replicate

Execute beaker-ts on any example to see the warning

**Comment by barnjamin** [comment]
What version are you running? I thought I'd fixed this in the last release

**Comment by aorumbayev** [comment]
@barnjamin invoking via npx so it grabs the latest

**Comment by aorumbayev** [comment]
maybe the very latest isn't on npm? 
0.0.81 is month ago
![Screenshot 2023-02-25 at 19 55 46](https://user-images.githubusercontent.com/7698600/221374737-a2000c6c-4cc7-4451-a6ca-239f23d65577.png)

**Comment by barnjamin** [comment]
https://github.com/algorand-devrel/beaker-ts/commit/163deea6f3ada3b215a118f287e2a495c3061115 this was the change that fixed these for me locally but maybe more have been deprecated since 🤔

**Comment by aorumbayev** [comment]
@barnjamin i think more have been deprecated - haven't seen these literally 3-4 days ago
