### ISSUE TITLE
Allowing to pass custom signer to the method calls 

### ISSUE THREAD

**Issue by aorumbayev** [algorand-devrel/beaker-ts#32]
In current implementation when instantiating the application client you can explicitly provide the signer which is then used for signing all abi calls (that internally generate app call transactions). 

However there are cases when an ABI calls (for example user facing calls that aren't meant to be signed by the creator or the app based on the initial signer value supplied to the constructor) need to sign the transactions. 

I believe its not currently possible to override and supply custom signer and sender fields via pre-generated wrappers that take care of assembling the method calls for atomic transaction composer. The way i handle it is basically manually create the app call myself with sender and signer set to whoever needs to do so for such method. 

Wondering if there are considerations to expand it in future allowing to pass custom signer for app calls

**Comment by barnjamin** [comment]
you're right, thats not ideal. It can be hacked around by using the ATC && `compose` calls ++ building the groups and combining manually right now but also terrible.

Will have a think about how to do this correctly
